### ISSUE TITLE
Create container with multiple network interfaces

### ISSUE THREAD

**Issue by rottenit** [bellackn/ansible-collection-homelab#16]
This could be just my inability to understand ansible but is there a way to specify multiple network interfaces during creation. For example I tried:

    proxmox_lxc_containers_present:
      - hostname: test1
        netif: |
         {"net0":"name=eth0,gw=192.168.0.1,ip=192.168.0.201/32,ip6=dhcp,bridge=vmbr1"}
         {"net217":"name=eth217,ip=dhcp,bridge=vmbr217"}

Which results in:
 msg: 'argument ''netif'' is of type <class ''str''> and we were unable to convert to dict: unable to evaluate string as dictionary'

Thanks!

**Comment by bellackn** [comment]
hi @rottenit, this should work:
```
netif: |
  {
    "net0":"name=eth0,gw=192.168.0.1,ip=192.168.0.201/32,ip6=dhcp,bridge=vmbr1",
    "net217":"name=eth217,ip=dhcp,bridge=vmbr217"
  }
```

**Comment by rottenit** [comment]
Thanks! that does work.

I did notice something interesting, the network ID must be between 1-99 otherwise you get:

400 Bad Request: Parameter verification failed. - {''net100'': ''property is not defined in schema and the schema does not allow additional properties''}'
