### ISSUE TITLE
Task "ping outside" truncates vmid's larger than 3 digits

### ISSUE THREAD

**Issue by rottenit** [bellackn/ansible-collection-homelab#17]
During the "Ping outside" task it fails if there are more than 3 digits in the vmid. See below:

vmid example: 9901

The command that gets executed truncates the last digit: 
invocation:
    module_args:
      _raw_params: lxc-attach -n 990 -- ping 8.8.8.8 -c 2

the command should read:
lxc-attach -n 9901 -- ping 8.8.8.8 -c 2

Otherwise proxmox will output the following errors:
lxc-attach: 990: ../src/lxc/attach.c: get_attach_context: 406 Connection refused - Failed to get init pid
lxc-attach: 990: ../src/lxc/attach.c: lxc_attach: 1470 Connection refused - Failed to get attach context

It would be beneficial to accept the same range of ID's that are possible in proxmox (1-999999999)

Thanks!

**Comment by bellackn** [comment]
hey, thanks for reporting, good catch! i have just pushed a fix to `main`. can you please try if that works for you? if it does, i'll release 5.2.1 afterwards.

**Comment by rottenit** [comment]
Looks like that fixed the issue!

**Comment by bellackn** [comment]
perfect, thanks for testing. release 5.2.1 incoming...
